import { readFile, writeFile, access } from 'node:fs/promises'
import { dirname, join, isAbsolute, resolve } from 'node:path'
import type { Writable } from 'node:stream'

/** All rules marky can migrate, keyed by uppercase markdownlint rule ID. */
const SUPPORTED_RULES: ReadonlyMap<
  string,
  { symbol: string; source: string; description: string }
> = new Map([
  [
    'MD001',
    {
      symbol: 'md001Rule',
      source: '@marky/compat-markdownlint',
      description: 'Heading levels increment by one',
    },
  ],
  [
    'MD009',
    {
      symbol: 'md009Rule',
      source: '@marky/core',
      description: 'No trailing spaces',
    },
  ],
  [
    'MD010',
    {
      symbol: 'md010Rule',
      source: '@marky/core',
      description: 'No hard tabs',
    },
  ],
  [
    'MD013',
    {
      symbol: 'md013Rule',
      source: '@marky/compat-markdownlint',
      description: 'Line length',
    },
  ],
  [
    'MD005',
    {
      symbol: 'md005Rule',
      source: '@marky/compat-markdownlint',
      description: 'Consistent list indentation at the same level',
    },
  ],
  [
    'MD007',
    {
      symbol: 'md007Rule',
      source: '@marky/compat-markdownlint',
      description: 'Unordered list indentation (default: 2 spaces per level)',
    },
  ],
  [
    'MD012',
    {
      symbol: 'md012Rule',
      source: '@marky/compat-markdownlint',
      description: 'Multiple consecutive blank lines',
    },
  ],
  [
    'MD022',
    {
      symbol: 'md022Rule',
      source: '@marky/compat-markdownlint',
      description: 'Blank lines around headings',
    },
  ],
  [
    'MD024',
    {
      symbol: 'md024Rule',
      source: '@marky/compat-markdownlint',
      description: 'No duplicate heading content',
    },
  ],
  [
    'MD025',
    {
      symbol: 'md025Rule',
      source: '@marky/compat-markdownlint',
      description: 'Single top-level heading per document',
    },
  ],
  [
    'MD026',
    {
      symbol: 'md026Rule',
      source: '@marky/compat-markdownlint',
      description: 'No trailing punctuation in headings',
    },
  ],
  [
    'MD031',
    {
      symbol: 'md031Rule',
      source: '@marky/compat-markdownlint',
      description: 'Blank lines around fenced code blocks',
    },
  ],
  [
    'MD032',
    {
      symbol: 'md032Rule',
      source: '@marky/compat-markdownlint',
      description: 'Blank lines around lists',
    },
  ],
  [
    'MD033',
    {
      symbol: 'md033Rule',
      source: '@marky/compat-markdownlint',
      description: 'No inline HTML',
    },
  ],
  [
    'MD034',
    {
      symbol: 'md034Rule',
      source: '@marky/compat-markdownlint',
      description: 'No bare URLs (use angle brackets or [text](url))',
    },
  ],
  [
    'MD040',
    {
      symbol: 'md040Rule',
      source: '@marky/compat-markdownlint',
      description: 'Fenced code blocks should have a language',
    },
  ],
  [
    'MD041',
    {
      symbol: 'md041Rule',
      source: '@marky/compat-markdownlint',
      description: 'First line heading',
    },
  ],
  [
    'MD047',
    {
      symbol: 'md047Rule',
      source: '@marky/compat-markdownlint',
      description: 'Files should end with a single newline',
    },
  ],
])

type RuleStatus = 'supported' | 'disabled' | 'unsupported'

interface RuleEntry {
  id: string
  status: RuleStatus
  symbol?: string
  source?: string
  description?: string
}

/**
 * Parse a markdownlint config file and classify each rule.
 */
function classifyRules(raw: Record<string, unknown>): RuleEntry[] {
  return Object.entries(raw).map(([id, value]) => {
    const normalized = id.toUpperCase()
    const mapping = SUPPORTED_RULES.get(normalized)
    if (!value) {
      return { id: normalized, status: 'disabled' }
    }
    if (mapping) {
      return { id: normalized, status: 'supported', ...mapping }
    }
    return { id: normalized, status: 'unsupported' }
  })
}

/**
 * Generate the content of a `marky.config.ts` file for the migrated rules.
 */
function generateConfig(entries: RuleEntry[]): string {
  const enabled = entries.filter((e) => e.status === 'supported')
  if (enabled.length === 0) {
    return `// marky.config.ts — generated by marky migrate
// No supported rules found — configure manually.
import type { MarkyConfig } from '@marky/core'

const config: MarkyConfig = {
  plugins: [],
}

export default config
`
  }

  // Group imports by source package
  const bySource = new Map<string, string[]>()
  for (const entry of enabled) {
    if (!entry.source || !entry.symbol) continue
    const existing = bySource.get(entry.source) ?? []
    existing.push(entry.symbol)
    bySource.set(entry.source, existing)
  }

  const importLines = [...bySource.entries()]
    .map(([pkg, symbols]) => `import { ${symbols.join(', ')} } from '${pkg}'`)
    .join('\n')

  const pluginList = enabled
    .filter((e) => e.symbol)
    .map((e) => `    ${e.symbol},`)
    .join('\n')

  return `// marky.config.ts — generated by marky migrate
${importLines}
import type { MarkyConfig } from '@marky/core'

const config: MarkyConfig = {
  plugins: [
${pluginList}
  ],
}

export default config
`
}

/**
 * Locate a markdownlint config file. Tries explicit `configPath` first,
 * then falls back to `.markdownlintrc` and `.markdownlint.json` in `cwd`.
 */
async function resolveConfigPath(
  configPath: string | undefined,
  cwd: string,
): Promise<string | null> {
  if (configPath) {
    const abs = isAbsolute(configPath) ? configPath : resolve(cwd, configPath)
    try {
      await access(abs)
      return abs
    } catch {
      return null
    }
  }
  for (const name of ['.markdownlintrc', '.markdownlint.json']) {
    const candidate = join(cwd, name)
    try {
      await access(candidate)
      return candidate
    } catch {
      // not found, try next
    }
  }
  return null
}

export interface MigrateIO {
  stdout: Writable
  stderr: Writable
  cwd: string
}

/**
 * Run the `marky migrate` action.
 */
export async function runMigrate(configPath: string | undefined, io: MigrateIO): Promise<number> {
  const resolved = await resolveConfigPath(configPath, io.cwd)
  if (!resolved) {
    const target = configPath ?? '.markdownlintrc / .markdownlint.json'
    io.stderr.write(`error: could not find config file: ${target}\n`)
    return 1
  }

  let raw: Record<string, unknown>
  try {
    const text = await readFile(resolved, 'utf8')
    raw = JSON.parse(text) as Record<string, unknown>
  } catch (err) {
    io.stderr.write(
      `error: failed to read ${resolved}: ${err instanceof Error ? err.message : String(err)}\n`,
    )
    return 1
  }

  const entries = classifyRules(raw)
  const supported = entries.filter((e) => e.status === 'supported')
  const unsupported = entries.filter((e) => e.status === 'unsupported')
  const disabled = entries.filter((e) => e.status === 'disabled')

  io.stdout.write(`Analyzing ${resolved}...\n\n`)

  if (supported.length > 0) {
    io.stdout.write('Supported rules (will be migrated):\n')
    for (const e of supported) {
      io.stdout.write(`  ✓ ${e.id}  →  ${e.symbol} from ${e.source}  (${e.description})\n`)
    }
    io.stdout.write('\n')
  }

  if (unsupported.length > 0) {
    io.stdout.write('Unsupported rules (require manual attention):\n')
    for (const e of unsupported) {
      io.stdout.write(`  ✗ ${e.id}  →  no marky equivalent yet\n`)
    }
    io.stdout.write('\n')
  }

  if (disabled.length > 0) {
    io.stdout.write(`Disabled rules (skipped): ${disabled.map((e) => e.id).join(', ')}\n\n`)
  }

  // Generate and write the config file
  const configContent = generateConfig(entries)
  const outputPath = join(dirname(resolved), 'marky.config.ts')
  await writeFile(outputPath, configContent, 'utf8')

  // Summary
  const migratedCount = supported.length
  const manualCount = unsupported.length
  const parts: string[] = []
  if (migratedCount > 0) {
    parts.push(`${migratedCount} ${migratedCount === 1 ? 'rule' : 'rules'} migrated`)
  }
  if (manualCount > 0) {
    parts.push(
      `${manualCount} ${manualCount === 1 ? 'rule requires' : 'rules require'} manual attention`,
    )
  }
  if (parts.length === 0) {
    parts.push('no enabled rules to migrate')
  }
  io.stdout.write(`Migration complete: ${parts.join(', ')}.\n`)
  io.stdout.write(`Generated: ${outputPath}\n`)

  return 0
}
